# Generated by Django 3.0.6 on 2020-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200515_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='country_wise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_cases', models.IntegerField(null=True)),
                ('total_des', models.IntegerField(null=True)),
                ('cases_yesterday', models.IntegerField(null=True)),
                ('des_yesterday', models.IntegerField(null=True)),
                ('rec_yesterday', models.IntegerField(null=True)),
                ('active_yesterday', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
