# Generated by Django 3.0.6 on 2020-05-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200515_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_wise',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country_wise',
            name='flag_url',
            field=models.CharField(max_length=110, null=True),
        ),
    ]
